@startuml binding

enum BoundNodeKind
struct Type{
    + kind : op_kind
    + size_bytes() : size_t
    + operator<<()
    + deduce_type<>() : Type
    + {static} from_string(std::string) : std::optional<Type>
}


abstract BoundNode {
    {abstract} + bound_node_kind() : BoundNodeKind 
    + is_statement() : bool 
    + is_expression() : bool 
}

struct BoundExpression{
    type : Type
}

struct BoundStatement

struct BoundExpressionStatement{
    expression : BoundExpression

    + bound_node_kind() : BoundNodeKind 
}

struct BoundBlockStatement{
    statements : List<BoundStatement>
    + bound_node_kind() : BoundNodeKind
}

struct BoundLiteralExpression {
    value : std::any

    + bound_node_kind() : BoundNodeKind
}

struct BoundBinaryExpression{
    left : BoundExpression
    right : BoundExpression
    op_kind : OperatorKind

    + bound_node_kind() : BoundNodeKind
    + deduce_type() : Type

}

struct BoundCastExpression{
    expression : BoundExpression

    + bound_node_kind() : BoundNodeKind
}

struct BoundVariableDeclarationStatement{
    variable_name : std::string
    type : Type
    is_constant : bool

    + bound_node_kind() : BoundNodeKind
    {abstract} + variable_declaration_statement_kind() : VariableDeclarationStatementKind
    {abstract} + size_bytes() : size_t
}

struct BoundVariableValueDeclarationStatement{
    initializer : BoundExpression

    + variable_declaration_statement_kind() : VariableDeclarationStatementKind
    + size_bytes() : size_t
}

struct BoundVariablePointerDeclarationStatement{
    initializer : BoundExpression

    + variable_declaration_statement_kind() : VariableDeclarationStatementKind
    + size_bytes() : size_t
}

struct BoundVariableStaticArrayDeclarationStatement{
    initializers : std::vector<BoundExpression>
    array_size : size_t

    + variable_declaration_statement_kind() : VariableDeclarationStatementKind
    + size_bytes() : size_t
}

BoundNode <|-- BoundStatement
BoundStatement <|-- BoundExpressionStatement
BoundStatement <|-- BoundBlockStatement
BoundStatement <|-- BoundVariableDeclarationStatement
BoundVariableDeclarationStatement <|-- BoundVariableValueDeclarationStatement
BoundVariableDeclarationStatement <|-- BoundVariablePointerDeclarationStatement
BoundVariableDeclarationStatement <|-- BoundVariableStaticArrayDeclarationStatement

BoundNode <|-- BoundExpression
BoundExpression <|-- BoundLiteralExpression
BoundExpression <|-- BoundBinaryExpression
BoundExpression <|-- BoundCastExpression


@enduml