name: build and deploy wasm

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: Release
      BUILD_THREADS: 16

    steps:
      - uses: actions/checkout@v3

      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v12

      - name: Build wasm
        run: ./build.sh wasm
        shell: bash

      - name: Save wasm build
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: build/wasm/web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        